# Generated by Django 5.0.1 on 2024-02-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
    ]
